#!/bin/bash

DEST_ROOT=../glpp/
# DEST_ROOT=build/lib/

mkdir -p ${DEST_ROOT}/include/glpp
mkdir -p ${DEST_ROOT}/src/gl2
mkdir -p ${DEST_ROOT}/src/gles2

cp assets/cpp/include/* ${DEST_ROOT}/include/glpp/
cp assets/cpp/src/common/* ${DEST_ROOT}/src/gles2/
cp assets/cpp/src/gles2/* ${DEST_ROOT}/src/gles2/
cp assets/cpp/src/common/* ${DEST_ROOT}src/gl2/
cp assets/cpp/src/gl2/* ${DEST_ROOT}/src/gl2/

python src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ${DEST_ROOT} --includesubdir include/glpp --sourcesubdir src --namespace gles2 --force --cpp --es2only
python src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ${DEST_ROOT} --includesubdir include/glpp --sourcesubdir src --namespace gl2 --force --cpp --gl2only

#  GLES2 interface
python src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ${DEST_ROOT} --includesubdir include/glpp --sourcesubdir src --namespace gles2 --force --cpp --es2only
# GL2 interface
python src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ${DEST_ROOT} --includesubdir include/glpp --sourcesubdir src --namespace gl2 --force --cpp --gl2only

# ANGLE extensions interface
python src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ${DEST_ROOT} --includesubdir include/glpp --sourcesubdir src --namespace "gles2:angle" --force --cpp --es2only --extensionsimportfile assets/extensions_angle_dx11.txt --extensionsoutputfilename extensions
# OSX extensions interface
python src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ${DEST_ROOT} --includesubdir include/glpp --sourcesubdir src --namespace "gl2:osx" --force --cpp --gl2only --extensionsimportfile assets/extensions_osx.txt --extensionsoutputfilename extensions
